# Generated by Django 5.0.6 on 2024-07-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateTimeField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.IntegerField()),
                ('thought_on_life', models.TextField()),
            ],
        ),
    ]
